export const assets = [
  {
    ticker: "BBAS3",
    score: 3,
    currPosition: 0.0849,
    target: 0,
    quantity: 220,
    price: 26.74,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
  {
    ticker: "ODPV3",
    score: 5,
    currPosition: 0.0849,
    target: 0,
    quantity: 450,
    price: 10.59,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
  {
    ticker: "WEGE3",
    score: 5,
    currPosition: 0.0849,
    target: 0,
    quantity: 450,
    price: 10.59,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
  {
    ticker: "KLBN3",
    score: 6,
    currPosition: 0.0849,
    target: 0,
    quantity: 450,
    price: 10.59,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
  {
    ticker: "BBSE3",
    score: 2,
    currPosition: 0.0849,
    target: 0,
    quantity: 450,
    price: 10.59,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
  {
    ticker: "ITSA4",
    score: 1,
    currPosition: 0.0849,
    target: 0,
    quantity: 450,
    price: 10.59,
    balance: 0,
    deviation: 0,
    quantityToTarget: 0,
    valueToTarget: 0,
  },
];
